/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.njuScrapalo;

import controler.dretve.DretvaAzuriranje;
import controler.misc.MetodeMisc;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import javax.swing.JPanel;
import javax.swing.JTextField;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;
import view.obrasci.ObrazacPostavki;

/**
 *
 * @author ahilis001
 */
public class Pocetna extends javax.swing.JFrame {
    
    //inicijalizacija postavki
    public static Properties postavke = new Properties();
    
    //inicijalizacija početnog jFramea
    public static Pocetna pocetna = new Pocetna(); 

    /**
     * Creates new form Pocetna
     */
    public Pocetna() {
        initComponents();
        MetodeMisc.ucitajKonfiguraciju();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtPoruke = new javax.swing.JTextField();
        jBtnPostavke = new javax.swing.JButton();
        jBtnOsvjezi = new javax.swing.JButton();
        jScrollPaneOglasi = new javax.swing.JScrollPane();
        jpPrikazOglasa = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jtPoruke.setText("Poruke");

        jBtnPostavke.setText("Postavke");
        jBtnPostavke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPostavkeActionPerformed(evt);
            }
        });

        jBtnOsvjezi.setText("Osvježi");
        jBtnOsvjezi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOsvjeziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jtPoruke, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnPostavke)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnOsvjezi)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jtPoruke, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBtnPostavke)
                .addComponent(jBtnOsvjezi))
        );

        jScrollPaneOglasi.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneOglasi.getVerticalScrollBar().setUnitIncrement(15);
        jScrollPaneOglasi.setAutoscrolls(true);

        jpPrikazOglasa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jpPrikazOglasaLayout = new javax.swing.GroupLayout(jpPrikazOglasa);
        jpPrikazOglasa.setLayout(jpPrikazOglasaLayout);
        jpPrikazOglasaLayout.setHorizontalGroup(
            jpPrikazOglasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        jpPrikazOglasaLayout.setVerticalGroup(
            jpPrikazOglasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        jScrollPaneOglasi.setViewportView(jpPrikazOglasa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneOglasi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneOglasi, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Klik na gomb Osvježi
     * ažurira oglase.
     * @param evt 
     */
    private void jBtnOsvjeziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOsvjeziActionPerformed
        MetodeMisc.azurirajOglase(pocetna);
    }//GEN-LAST:event_jBtnOsvjeziActionPerformed

    /**
     * Klik na gumb Postavke
     * @param evt 
     */
    private void jBtnPostavkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPostavkeActionPerformed
        
        //kreiranje i prikaz obrasca postavki
        ObrazacPostavki opPostavke = new ObrazacPostavki();
        opPostavke.generirajObrazac();
    }//GEN-LAST:event_jBtnPostavkeActionPerformed

    /**
     * Pokretanje dretve osvježavanja oglasa
     */
    static void pokreniDretvu(){
        DretvaAzuriranje.getDretva().start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        pokreniDretvu();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                pocetna.setVisible(true);
            }
        });
    }

    /**
     * Metoda za mijenjanje i prikaz poruka.
     * @param strPoruka 
     */
    public static void prikaziPoruku(String strPoruka){
        SimpleDateFormat formatter = new SimpleDateFormat("dd.MM.yyyy. HH:mm:ss");
        Pocetna.getJtPoruke().setText(formatter.format(new Date(System.currentTimeMillis())) + " - " + strPoruka);
    }

    public static Pocetna getPocetna() {
        return pocetna;
    }

    public static void setPocetna(Pocetna pocetna) {
        Pocetna.pocetna = pocetna;
    }
    
    public static Properties getPostavke() {
        return postavke;
    }

    public static void setPostavke(Properties postavke) {
        Pocetna.postavke = postavke;
    }

    public static JTextField getJtPoruke() {
        return jtPoruke;
    }

    public static JPanel getJpPrikazOglasa() {
        return jpPrikazOglasa;
    }

    public static void setJpPrikazOglasa(JPanel jpPrikazOglasa) {
        Pocetna.jpPrikazOglasa = jpPrikazOglasa;
    }

    public static void setJtPoruke(JTextField jtPoruke) {
        Pocetna.jtPoruke = jtPoruke;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton jBtnOsvjezi;
    private static javax.swing.JButton jBtnPostavke;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneOglasi;
    private static javax.swing.JPanel jpPrikazOglasa;
    private static javax.swing.JTextField jtPoruke;
    // End of variables declaration//GEN-END:variables

    
}
